apiVersion: v1
kind: Service
metadata:
  name: brand-service-mongo
  labels:
    app: brand-service
spec:
  ports:
    - port: 27017
  selector:
    app: brand-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-service-mongo-deployment
  labels:
    app: brand-service
spec:
  selector:
    matchLabels:
      app: brand-service
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: brand-service
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017 
          name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-service-server-deployment
  labels:
    app: brand-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brand-service-server
  template:
    metadata:
      labels:
        app: brand-service-server
    spec:
      containers:
      - name: brand-service-server
        image: pieterpa/brand-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8052
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: MONGODB_HOST
          value: "brand-service-mongo"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:                     
  name: brand-service-server
  labels:
    app: brand-service-server
spec:                         
  type: NodePort
  selector:
    app: brand-service-server
  ports:
  - name: http
    port: 8052
    targetPort: 8052
